name: MacOS (make with BTADDON) Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Update brew repos
      run: brew update
    - name: Tap RfidResearchGroup/proxmark3
      run: brew tap RfidResearchGroup/proxmark3
    - name: Install dependencies
      run: brew install readline qt5 RfidResearchGroup/proxmark3/arm-none-eabi-gcc
    - name: Build
      run: make clean && make V=1 PLATFORM_EXTRAS=BTADDON
    - name: Test
      run: make check
