name: Ubuntu (make with BTADDON) Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Update apt repos
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -yqq make autoconf build-essential ca-certificates pkg-config libreadline-dev gcc-arm-none-eabi libnewlib-dev qtbase5-dev libbz2-dev libbluetooth-dev libpython3-dev python3 python3-dev libpython3-all-dev liblua5.2-dev liblua5.2-0-dbg liblua5.2-0 lua5.2 sed
    - name: Build
      run: make clean && make V=1 PLATFORM_EXTRAS=BTADDON
    - name: Test
      run: make check
